version: '3'
services:
  frontend:
    image: asrith1158/frontend-image:latest
    ports:
      - '3000:3000'
  backend:
    image: asrith1158/backend-image:latest
    ports:
      - '8080:8080'
    environment:
      - REACT_APP_CLOUDINARY_CLOUD_NAME = dd4osfetw
      - REACT_APP_BACKEND_URL = http://localhost:8080
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb+srv://asrithnune03:asrithrishi@discuss.lieci.mongodb.net/?retryWrites=true&w=majority&appName=DiscUss
      - JWT_SECRET_KEY='jhdcjhsdvchjsdhbfasdgbvs'
      - PORT=8080