apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asrith1158/backend-image:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mern-backend-secret
                  key: MONGODB_URI
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mern-backend-secret
                  key: JWT_SECRET_KEY
